inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.0

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 125

Metrics/ParameterLists:
  Exclude:
    - lib/atol/request/post_document/item/body.rb